version: '3'
services: 
  app:
    image: 'golang:1.15.8'
    ports:
      - '8080:8080'
    volumes: 
      - .:/myapp
    working_dir: /myapp
    tty: true
    networks: 
      - network
    depends_on: 
      - 'db'
  db:
    image: 'mysql:8'
    container_name: godockerDB
    ports:
    - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - network

networks:
  network:
    driver: bridge