version: '3'
services: 
  app:
    image: 'golang:1.15.8'
    ports:
      - '8080:8080'
    volumes: 
      - .:/myapp
    working_dir: /myapp
    tty: true
    networks: 
      - network
    depends_on: 
      - 'db'
  db:
    image: 'mysql:8'
    container_name: godockerDB
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./config/my.conf:/etc/mysql/conf.d/my.cnf
    ports:
    - '3306:3306'
    environment:
      MYSQL_HOST_AUTH_METHOD: 'trust'
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - network

networks:
  network:
    driver: bridge